### ISSUE TITLE
Tweetinvi 3.0 FilteredStreams not working

### ISSUE THREAD

**Issue by jxlarrea** [linvi/tweetinvi#732]
I've been porting some projects to .Net Core 2.1 and found that FilteredStreams does not work anymore. A connection is established to the stream (as I can see KEEP ALIVE events being fired) but no matching tweet is ever received. MatchingTweetReceived and NonMatchingTweetReceived are never triggered.

Tested on .Net Core 2.1 and .Net Framework 4.7, both platforms have the issue.

Reverting to Tweetinvi 2.1.0 fixed the problem.

**Comment by Tearth** [comment]
Same issue. Everything works good on Windows 10, but when I deployed app on Linux (Arch), streams stopped working. I switched back to 2.1.0 and we will see if it works now.

**Comment by jxlarrea** [comment]
I see that Tweetinvi 4.0 has been release but I don't see any mention of this bug being fixed anywhere. @linvi could you please confirm?

**Comment by jxlarrea** [comment]
@linvi I just tested it. It is still broken in Tweetinvi 4.0. The last time FilteredStreams worked was in Tweetinvi 2.1.

**Comment by linvi** [comment]
I can confirm that i did not have time to solve this issue. 

4.0 is a release to make sure that the changes for Direct Messages and UserStream are properly supported by Tweetinvi.

I am trying to keep up with the different tasks but unfortunately I am very busy and I try to prioritise as well as I can. 

I will make sure to have a look before releasing version 5.0.

**Comment by linvi** [comment]
Hello,

I have created successfully a sample console app on Ubuntu 18.04.1.
Could you please come back to me and let me know if you can make this app work on your side?

> Run `dotnet run`.

``` c#
// Program.cs
using System;
using Tweetinvi;
using Tweetinvi.Models;

namespace test_tweetinvi
{
    class Program
    {
        static void Main(string[] consoleArgs)
        {
            Console.WriteLine("Hello World!");

            var credentials = new TwitterCredentials()
            {
                ConsumerKey = "xxxx",
                ConsumerSecret = "xxxx",
                AccessToken = "xxxx",
                AccessTokenSecret = "xxxx"
            };

            var fs = Stream.CreateFilteredStream(credentials);
            fs.AddTrack("github");

            fs.MatchingTweetReceived += (evnt, args) =>
            {
                Console.WriteLine(args.Tweet);
            };

            try
            {
                fs.StartStreamMatchingAllConditions();
            }
            catch (System.Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }
    }
}
```

``` csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="tweetinviapi" Version="4.0.0" />
  </ItemGroup>
</Project>
```

**Comment by linvi** [comment]
Please reopen if you keep encountering this problem but without further details as to which platform/configuration the project is not working I won't be able to reproduce and therefore won't be able to fix it.

**Comment by jxlarrea** [comment]
> Please reopen if you keep encountering this problem but without further details as to which platform/configuration the project is not working I won't be able to reproduce and therefore won't be able to fix it.

Hi @linvi,

Actually I think I found the problem. When more than 1 language filters are added to the stream, the issue occurs - MatchingTweetReceived is never fired. This happens in Tweetinvi versions 3.0 and above. 2.1 Works fine.

```csharp
using System;
using Tweetinvi;
using Tweetinvi.Models;

namespace Tweetinvi_Test
{
    internal class Program
    {
        private static void Main(string[] consoleArgs)
        {
            var credentials = new TwitterCredentials()
            {
                ConsumerKey = "xxx",
                ConsumerSecret = "xxx",
                AccessToken = "xxx",
                AccessTokenSecret = "xxx"
            };

            var fs = Stream.CreateFilteredStream(credentials);
            fs.StallWarnings = true;
            fs.AddTrack("github");
           
            fs.AddTweetLanguageFilter(LanguageFilter.English);
            fs.AddTweetLanguageFilter(LanguageFilter.Spanish);             

            fs.MatchingTweetReceived += (evnt, args) =>
            {
                Console.WriteLine(args.Tweet);
            };

            fs.KeepAliveReceived += (sender, args) =>
            {
                Console.WriteLine("KEEP ALIVE RECIEVED");
            };

            fs.DisconnectMessageReceived += (sender, args) =>
            {
                Console.WriteLine("DisconnectMessageReceived " + args.DisconnectMessage);
            };

            fs.WarningFallingBehindDetected += (sender, args) =>
            {
                Console.WriteLine("WarningFallingBehindDetected " + args.WarningMessage);
            };

            fs.StreamStopped += (sender, args) =>
            {
                Console.WriteLine("StreamStopped " + args.DisconnectMessage);
            };

            fs.StartStreamMatchingAllConditions();
        }
    }
}
```
